name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: sudo apt-get update && sudo apt-get install -y libgl1
      - run: pip install -r requirements.txt
      - run: pip install pre-commit coverage bandit
      - run: pre-commit run --all-files --show-diff-on-failure
      - run: pytest --cov=. -q
      - run: bandit -r .
